apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: simple-app-gateway
  namespace: canary-demo
  labels:
    app: simple-app
spec:
  selector:
    istio: ingressgateway # Use Istio default controller
  servers:
  - port:
      number: 90
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: simple-app-tls # Secret containing TLS certificate
    hosts:
    - "*"